databases:
  - name: npsp_rails_db
    databaseName: npsp_rails_production
    user: npsp_rails

services:
  - type: web
    name: npsp-rails-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: npsp_rails_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
